# Generated by Django 4.2.4 on 2023-08-29 13:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookstore.user')),
                ('expiry_date', models.DateTimeField()),
                ('value', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
