# Generated by Django 4.2.4 on 2023-08-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
